Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 35

AllCops:
  Exclude:
    - db/migrate/*.rb
    - db/schema.rb
    - db/seeds.rb
    - db/structure.sql
    - bin/*
    - script/*
    - config/routes.rb
    - config/initializers/simple_form_bootstrap.rb

Style/Lambda:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false